# Generated by Django 4.2.16 on 2025-01-06 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLocInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('size_charger', models.CharField(max_length=100)),
                ('num_charger', models.IntegerField()),
                ('budget', models.FloatField()),
                ('POI', models.CharField(max_length=100)),
                ('ROI', models.FloatField()),
                ('is_premium', models.BooleanField(default=False, verbose_name='Is this a premium location?')),
                ('user', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
