# Generated by Django 4.2.17 on 2025-01-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPriceAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceHV', models.FloatField(default=47621.48)),
                ('pricetr100', models.FloatField(default=494589.76)),
                ('pricetr160', models.FloatField(default=594384.0)),
                ('pricetr250', models.FloatField(default=705095.1)),
                ('pricetr315', models.FloatField(default=1192509.79)),
                ('priceTRtoMDB', models.FloatField(default=280.0)),
                ('priceMDBtoEV', models.FloatField(default=280.0)),
                ('priceEV7', models.FloatField(default=21900.0)),
                ('priceEV22', models.FloatField(default=0.0)),
                ('pricePackage', models.FloatField(default=16100.0)),
                ('package', models.CharField(choices=[('addpackage', 'รวม'), ('nonpackage', 'ไม่รวม')], default=1, max_length=100)),
            ],
        ),
    ]
