# Generated by Django 4.2.17 on 2025-01-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_datapriceac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon1', models.IntegerField(default=330)),
                ('addon2', models.IntegerField(default=550)),
                ('addon3', models.IntegerField(default=220)),
                ('addon4', models.IntegerField(default=330)),
                ('addon5', models.IntegerField(default=810)),
                ('addon6', models.IntegerField(default=1300)),
                ('addon7', models.IntegerField(default=1400)),
                ('addon8', models.IntegerField(default=1650)),
                ('addon9', models.IntegerField(default=3750)),
                ('addon10', models.IntegerField(default=6450)),
                ('addon11', models.IntegerField(default=5350)),
                ('addon12', models.IntegerField(default=1650)),
                ('addon13', models.IntegerField(default=23600)),
                ('addon14', models.IntegerField(default=23600)),
                ('addon15', models.IntegerField(default=6450)),
            ],
        ),
        migrations.CreateModel(
            name='DataCostElecAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField(default=0.2)),
                ('unnitperhour', models.FloatField(default=7.0)),
                ('dayserviceperyear', models.IntegerField(default=120)),
                ('price22onpeak', models.FloatField(default=4.1839)),
                ('priceless22onpeak', models.FloatField(default=4.3297)),
                ('price22offpeak', models.FloatField(default=2.6037)),
                ('priceless22offpeak', models.FloatField(default=2.6369)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=2590, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
