# Generated by Django 5.1.4 on 2025-01-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_payback_period_calcostac_cal_costtotal_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcostac',
            name='addon_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calcostac',
            name='costtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calcostac',
            name='disthvtotr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calcostac',
            name='distmdbtoev',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calcostac',
            name='distrtomdb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calcostac',
            name='numev',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calcostac',
            name='packageadd',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='calcostac',
            name='price_ev_7kw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='calcostac',
            name='size_tr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='calcostac',
            name='cal_costtotal_addon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
